#!/bin/bash
gcc -c tst.c -Ilibavcodec -Ilibavutil     
gcc tst.o libavcodec/libavcodec.a libavutil/libavutil.a -o tst -lm


#./configure  --disable-decoders --disable-ffserver --disable-zlib --disable-devices --disable-bsfs --disable-encoders --disable-demuxers --disable-parsers --disable-protocols --disable-muxers --disable-ipv6 --disable-network --enable-parser=h263 --enable-parser=mpeg4video  --enable-decoder=h263 --enable-decoder=vc1 --enable-decoder=wmv3
